/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managePanels;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sushm
 */
public class MngDeliveryManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MngDeliveryManJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAcc;
    
    public MngDeliveryManJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        populateTblDMList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDMBack = new javax.swing.JButton();
        lblMainMR = new javax.swing.JLabel();
        lblDMName = new javax.swing.JLabel();
        lblDMUsername = new javax.swing.JLabel();
        lblDMPassword = new javax.swing.JLabel();
        txtfDMName = new javax.swing.JTextField();
        txtfDMUsername = new javax.swing.JTextField();
        txtfDMPassword = new javax.swing.JTextField();
        btnDMRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDMList = new javax.swing.JTable();
        btnDMEdit = new javax.swing.JButton();
        btnDMDelete = new javax.swing.JButton();
        btnDMSave = new javax.swing.JButton();
        lblDMAddress = new javax.swing.JLabel();
        txtfDMAddress = new javax.swing.JTextField();
        lblDMPhnumber = new javax.swing.JLabel();
        txtfDMPhnumber = new javax.swing.JTextField();

        btnDMBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDMBack.setText("<");
        btnDMBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMBackActionPerformed(evt);
            }
        });

        lblMainMR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMainMR.setText("Manage Delivery Man");

        lblDMName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMName.setText("Name:");

        lblDMUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMUsername.setText("Username:");

        lblDMPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMPassword.setText("Password:");

        txtfDMUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDMUsernameActionPerformed(evt);
            }
        });

        btnDMRegister.setText("Register");
        btnDMRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMRegisterActionPerformed(evt);
            }
        });

        tblDMList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblDMList);

        btnDMEdit.setText("Edit");
        btnDMEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMEditActionPerformed(evt);
            }
        });

        btnDMDelete.setText("Delete");
        btnDMDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMDeleteActionPerformed(evt);
            }
        });

        btnDMSave.setText("Save");
        btnDMSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMSaveActionPerformed(evt);
            }
        });

        lblDMAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMAddress.setText("Address:");

        txtfDMAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDMAddressActionPerformed(evt);
            }
        });

        lblDMPhnumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMPhnumber.setText("PhNumber:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDMBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMainMR, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblDMName)
                        .addGap(46, 46, 46)
                        .addComponent(txtfDMName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblDMUsername)
                        .addGap(22, 22, 22)
                        .addComponent(txtfDMUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDMEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnDMDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnDMSave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDMPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtfDMPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDMAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtfDMAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDMPhnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfDMPhnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnDMRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDMBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMainMR, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblDMName))
                    .addComponent(txtfDMName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDMUsername))
                    .addComponent(txtfDMUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDMPassword))
                    .addComponent(txtfDMPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDMAddress))
                    .addComponent(txtfDMAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDMPhnumber))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtfDMPhnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDMRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDMEdit)
                    .addComponent(btnDMDelete)
                    .addComponent(btnDMSave))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDMBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLout = (CardLayout) userProcessContainer.getLayout();
        cardLout.previous(userProcessContainer);
    }//GEN-LAST:event_btnDMBackActionPerformed

    private void txtfDMUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDMUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDMUsernameActionPerformed

    private void btnDMRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMRegisterActionPerformed
        // TODO add your handling code here:
        if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtfDMName.getText())){
            UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(txtfDMName.getText(), txtfDMUsername.getText(), txtfDMPassword.getText(), null, new DeliverManRole());
            DeliveryMan dm = ecosystem.getDeliveryManDirectory().createUserAccount(txtfDMName.getText(), txtfDMUsername.getText(), txtfDMPassword.getText(),txtfDMAddress.getText(),txtfDMPhnumber.getText());
            populateTblDMList();
            txtfDMName.setText("");
            txtfDMUsername.setText("");
            txtfDMPassword.setText("");
            txtfDMAddress.setText("");
            txtfDMPhnumber.setText("");

        }
        else{
            JOptionPane.showMessageDialog(null, "Username exists! Please provide the different one!");
        }
    }//GEN-LAST:event_btnDMRegisterActionPerformed

    private void btnDMEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMEditActionPerformed
        // TODO add your handling code here:
        int highlightedRow = tblDMList.getSelectedRow();
        UserAccountDirectory userAcc = ecosystem.getUserAccountDirectory();
        if(highlightedRow >= 0){
            String username = (String) tblDMList.getValueAt(highlightedRow, 1);
            DeliveryMan dm = ecosystem.getDeliveryManDirectory().getDeliveryMan(username);
            txtfDMName.setText(dm.getName());
            txtfDMUsername.setText(dm.getUserName());
            txtfDMPassword.setText(dm.getPassword());
            this.userAcc = ecosystem.getUserAccountDirectory().authenticateUser(username, dm.getPassword());
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the desired row to edit");
        }
    }//GEN-LAST:event_btnDMEditActionPerformed

    private void btnDMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMDeleteActionPerformed
        // TODO add your handling code here:
        int highlightedRow = tblDMList.getSelectedRow();
        if(highlightedRow >= 0){
            String username = (String) tblDMList.getValueAt(highlightedRow, 1);
            ecosystem.getDeliveryManDirectory().deleteDeliveryMan(username);
            ecosystem.getUserAccountDirectory().deleteUserAccount(userAcc);
            populateTblDMList();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the row to delete");
        }
    }//GEN-LAST:event_btnDMDeleteActionPerformed

    private void btnDMSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMSaveActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory userAcc = ecosystem.getUserAccountDirectory();
        ecosystem.getUserAccountDirectory().editUserAccount(this.userAcc,txtfDMName.getText(), txtfDMUsername.getText(), txtfDMPassword.getText());
        ecosystem.getDeliveryManDirectory().editDeliveryMan(txtfDMName.getText(), txtfDMUsername.getText(), txtfDMPassword.getText());
        txtfDMName.setText("");
        txtfDMUsername.setText("");
        txtfDMPassword.setText("");
        populateTblDMList();

    }//GEN-LAST:event_btnDMSaveActionPerformed

    private void txtfDMAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDMAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDMAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDMBack;
    private javax.swing.JButton btnDMDelete;
    private javax.swing.JButton btnDMEdit;
    private javax.swing.JButton btnDMRegister;
    private javax.swing.JButton btnDMSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDMAddress;
    private javax.swing.JLabel lblDMName;
    private javax.swing.JLabel lblDMPassword;
    private javax.swing.JLabel lblDMPhnumber;
    private javax.swing.JLabel lblDMUsername;
    private javax.swing.JLabel lblMainMR;
    private javax.swing.JTable tblDMList;
    private javax.swing.JTextField txtfDMAddress;
    private javax.swing.JTextField txtfDMName;
    private javax.swing.JTextField txtfDMPassword;
    private javax.swing.JTextField txtfDMPhnumber;
    private javax.swing.JTextField txtfDMUsername;
    // End of variables declaration//GEN-END:variables

    private void populateTblDMList() {
        
        ArrayList<DeliveryMan> dmDirectory = ecosystem.getDeliveryManDirectory().getDeliveryManDirectory();
        DefaultTableModel tableModel = (DefaultTableModel)tblDMList.getModel();
        tableModel.setRowCount(0);
        
        for(DeliveryMan dm: dmDirectory){
        
            Object [] row = new Object[3];
            row[0] = dm.getName();
            row[1] = dm.getUserName();
            row[2] = dm.getPassword();
            tableModel.addRow(row);
        }
    }
}
