/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sushm
 */
public class ManageRestInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestInfoJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount account;
    
    
    public ManageRestInfoJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;
        txtfMRIUsername.setText(account.getUsername());
        fillTextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMRIAddress = new javax.swing.JLabel();
        txtfMRIRestaurantName = new javax.swing.JTextField();
        txtfMRIPhoneNumber = new javax.swing.JTextField();
        txtfMRIAddress = new javax.swing.JTextField();
        lblRestInfo = new javax.swing.JLabel();
        btnMRIUpdate = new javax.swing.JButton();
        btnMRISave = new javax.swing.JButton();
        lblMRIUsername = new javax.swing.JLabel();
        txtfMRIUsername = new javax.swing.JTextField();
        lblRestName = new javax.swing.JLabel();
        btnMRIBack = new javax.swing.JButton();
        lblPhnum = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMRIAddress.setText("Address:");
        jPanel2.add(lblMRIAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 210, 104, -1));

        txtfMRIRestaurantName.setEnabled(false);
        jPanel2.add(txtfMRIRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 126, 143, -1));

        txtfMRIPhoneNumber.setEnabled(false);
        jPanel2.add(txtfMRIPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 167, 143, -1));

        txtfMRIAddress.setEnabled(false);
        jPanel2.add(txtfMRIAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 207, 143, -1));

        lblRestInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRestInfo.setText("Restaurant Info");
        jPanel2.add(lblRestInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 14, 159, -1));

        btnMRIUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnMRIUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnMRIUpdate.setText("Update");
        btnMRIUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRIUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnMRIUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 262, -1, -1));

        btnMRISave.setBackground(new java.awt.Color(0, 0, 0));
        btnMRISave.setForeground(new java.awt.Color(255, 255, 255));
        btnMRISave.setText("Save");
        btnMRISave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRISaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnMRISave, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 262, 67, -1));

        lblMRIUsername.setText("User Name:");
        jPanel2.add(lblMRIUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 91, 104, -1));

        txtfMRIUsername.setEnabled(false);
        jPanel2.add(txtfMRIUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 88, 143, -1));

        lblRestName.setText("Restaurant Name:");
        jPanel2.add(lblRestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 129, 104, -1));

        btnMRIBack.setBackground(new java.awt.Color(0, 0, 0));
        btnMRIBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMRIBack.setForeground(new java.awt.Color(255, 255, 255));
        btnMRIBack.setText("<");
        btnMRIBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRIBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnMRIBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblPhnum.setText("Phone Number:");
        jPanel2.add(lblPhnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 170, 104, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMRIUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRIUpdateActionPerformed
        // TODO add your handling code here:
        txtfMRIPhoneNumber.setEnabled(true);
        txtfMRIRestaurantName.setEnabled(true);
        txtfMRIAddress.setEnabled(true);
        btnMRIUpdate.setEnabled(false);
    }//GEN-LAST:event_btnMRIUpdateActionPerformed

    private void btnMRISaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRISaveActionPerformed
        // TODO add your handling code here:

        for(Restaurant restro: ecosystem.getRestaurantDirectory().getRestaurantDirectory()){
            if(restro.getUserName().equals(account.getUsername())){
                ecosystem.getRestaurantDirectory().updateRestaurantInfo(restro, txtfMRIRestaurantName.getText(), txtfMRIPhoneNumber.getText(), txtfMRIAddress.getText());
            }
        }

        btnMRIUpdate.setEnabled(true);
        txtfMRIRestaurantName.setEnabled(false);
        txtfMRIAddress.setEnabled(false);
        txtfMRIPhoneNumber.setEnabled(false);
    }//GEN-LAST:event_btnMRISaveActionPerformed

    private void btnMRIBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRIBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnMRIBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMRIBack;
    private javax.swing.JButton btnMRISave;
    private javax.swing.JButton btnMRIUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMRIAddress;
    private javax.swing.JLabel lblMRIUsername;
    private javax.swing.JLabel lblPhnum;
    private javax.swing.JLabel lblRestInfo;
    private javax.swing.JLabel lblRestName;
    private javax.swing.JTextField txtfMRIAddress;
    private javax.swing.JTextField txtfMRIPhoneNumber;
    private javax.swing.JTextField txtfMRIRestaurantName;
    private javax.swing.JTextField txtfMRIUsername;
    // End of variables declaration//GEN-END:variables

    private void fillTextFields() {
        for(Restaurant restaurant: ecosystem.getRestaurantDirectory().getRestaurantDirectory()){
            if(restaurant.getUserName().equals(account.getUsername())){
                txtfMRIRestaurantName.setText(restaurant.getName());
                txtfMRIAddress.setText(restaurant.getAddress());
               txtfMRIPhoneNumber.setText(restaurant.getNumber());
            }
        }        
    }
}
